### PR TITLE
fix: :bug: button types

### PR DESCRIPTION
**Pull request by AdrianValdes**

### CODE REVIEW

**Comment by AdrianValdes** [comment]
In case you feel like reading some of these days, [this](https://dev.to/bytebodger/default-props-in-react-typescript-2o5o) article talks a lot about the default props issue. The author rejects the idea of using an interface and default function parameters, that threw me of too. Although now that I double check his example is slightly different.

**Comment by AdrianValdes** [comment]
I pushed a lot yesterday morning or before, but I forgot to put you as a reviewer. I am going to kill myself! To be like that makes me crazy. I saw you change the title, it makes sense not to repeat fix.

**Review by paschalidi — APPROVED** [review]
Good stuff! Lets move into the gh actions next :)

**Comment by paschalidi** [comment]
Want to delete your branches ;) @AdrianValdes 
image

**Comment by AdrianValdes** [comment]
All of them?

**Comment by paschalidi** [comment]
The ones that are merged. Dont delete them locally from your machine but from github

**Pull request merged**
